### ISSUE TITLE
/config

### ISSUE THREAD

**Issue by Keyrxng** [ubq-testing/bot-ai#22]
new /config command for admins to adjust the config using NLP

**Comment by ghost** [comment]
Not implemented yet.

**Comment by ghost** [comment]
Not implemented yet.

**Comment by ghost** [comment]
```diff
- Invalid merged configuration
```
```json
{
  "errorMessage": ".labels.time.0 must be string\n.labels.time.1 must be string\n.labels.time.2 must be string\n.labels.time.3 must be string\n.labels.time.4 must be string\n.labels.priority.0 must be string\n.labels.priority.1 must be string\n.labels.priority.2 must be string\n.labels.priority.3 must be string\n.labels.priority.4 must be string",
  "caller": "generateConfiguration",
  "revision": "d00946c8"
}
```

**Comment by ghost** [comment]
```diff
- Invalid merged configuration
```
```json
{
  "errorMessage": ".labels.time.0 must be string\n.labels.time.1 must be string\n.labels.time.2 must be string\n.labels.time.3 must be string\n.labels.time.4 must be string\n.labels.priority.0 must be string\n.labels.priority.1 must be string\n.labels.priority.2 must be string\n.labels.priority.3 must be string\n.labels.priority.4 must be string",
  "caller": "generateConfiguration",
  "revision": "d00946c8"
}
```

**Comment by ghost** [comment]
### Available Commands

| Command | Description | Example |
| --- | --- | --- |
| `/start` | Assign yourself to the issue. | /start |
| `/stop` | Unassign yourself from the issue. | /stop |
| `/help` | List all available commands. | /help |
| `/autopay` | Toggle automatic payment for the completion of the current issue. | /autopay true |
| `/query` | Returns the user's wallet, access, and multiplier information. | /query @user |
| `/ask` | Ask a context aware question. | /ask is x or y the best approach? |
| `/multiplier` | Set the task payout multiplier for a specific contributor, and provide a reason for why. | /multiplier @user 0.5 "multiplier<br>reason" |
| `/labels` | Set access control, for admins only. | /labels @user priority time<br>price |
| `/authorize` | Approve a label change, for admins only. | /authorize |
| `/wallet` | Register your wallet address for payments. | /wallet ubq.eth |
